server:
  port: 8081

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: trading-engine-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54321/trading_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: trading-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  platform:
    token-account: ${PLATFORM_TOKEN_ACCOUNT:Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS}

trading:
  volatility:
    threshold: 0.20
    window-size: 10
  app:
    platform-wallet: Platform111111111111111111111111111111111

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
