apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
    spec:
      containers:
      - name: trading-engine
        image: trading-engine:local-testing
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: DB_URL
          value: jdbc:postgresql://postgres:5432/platform
        - name: KAFKA_BROKERS
          value: kafka-service:9092
        - name: PLATFORM_TOKEN_ACCOUNT
          value: "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
        - name: REDIS_HOST
          value: redis-service
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: trading-engine-config
---
apiVersion: v1
kind: Service
metadata:
  name: trading-engine
spec:
  selector:
    app: trading-engine
  ports:
  - port: 8081
    targetPort: 8081
